local allWeaponHashes = {"WEAPON_COMPACTRIFLE", "WEAPON_PETROLCAN", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_PUMPSHOTGUN", "WEAPON_VINTAGEPISTOL", "WEAPON_MACHETE", "WEAPON_DOUBLEACTION", "WEAPON_STONE_HATCHET", "WEAPON_PRECISIONRIFLE", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE", "WEAPON_FLASHLIGHT", "WEAPON_ADVANCEDRIFLE", "WEAPON_MINIGUN", "WEAPON_COMBATSHOTGUN", "WEAPON_SMG", "WEAPON_BATTLEAXE", "WEAPON_MG", "WEAPON_RPG", "WEAPON_PISTOL50", "WEAPON_GRENADE", "WEAPON_BZGAS", "WEAPON_COMPACTLAUNCHER", "WEAPON_POOLCUE", "WEAPON_GRENADELAUNCHER", "WEAPON_DAGGER", "WEAPON_CANDYCANE", "WEAPON_BALL", "WEAPON_RAILGUNXM3", "WEAPON_SMOKEGRENADE", "WEAPON_MUSKET", "WEAPON_PIPEBOMB", "WEAPON_BULLPUPSHOTGUN", "WEAPON_HATCHET", "WEAPON_SNSPISTOL", "WEAPON_MARKSMANRIFLE_MK2", "WEAPON_HAMMER", "WEAPON_ASSAULTSMG", "WEAPON_COMBATPDW", "WEAPON_CROWBAR", "WEAPON_PISTOL", "WEAPON_DBSHOTGUN", "WEAPON_EMPLAUNCHER", "WEAPON_BAT", "WEAPON_REVOLVER", "WEAPON_ASSAULTSHOTGUN", "WEAPON_NAVYREVOLVER", "WEAPON_SNSPISTOL_MK2", "WEAPON_WRENCH", "WEAPON_COMBATMG_MK2", "WEAPON_ACIDPACKAGE", "WEAPON_RAYPISTOL", "WEAPON_MARKSMANPISTOL", "WEAPON_MACHINEPISTOL", "WEAPON_KNUCKLE", "WEAPON_HEAVYPISTOL", "WEAPON_PROXMINE", "WEAPON_SNOWBALL", "WEAPON_HEAVYSHOTGUN", "WEAPON_REVOLVER_MK2", "WEAPON_HEAVYRIFLE", "WEAPON_MARKSMANRIFLE", "WEAPON_SWITCHBLADE", "WEAPON_GADGETPISTOL", "WEAPON_FERTILIZERCAN", "WEAPON_PISTOL_MK2", "WEAPON_RAILGUN", "WEAPON_AUTOSHOTGUN", "WEAPON_RAYCARBINE", "WEAPON_STUNGUN", "WEAPON_ASSAULTRIFLE", "WEAPON_SPECIALCARBINE", "WEAPON_MINISMG", "WEAPON_CERAMICPISTOL", "WEAPON_TACTICALRIFLE", "WEAPON_BOTTLE", "WEAPON_FIREEXTINGUISHER", "WEAPON_RAYMINIGUN", "WEAPON_BULLPUPRIFLE", "WEAPON_FLARE", "WEAPON_CARBINERIFLE_MK2", "WEAPON_MILITARYRIFLE", "WEAPON_PISTOLXM3", "WEAPON_SMG_MK2", "WEAPON_STICKYBOMB", "WEAPON_MICROSMG", "WEAPON_STUNGUN_MP", "WEAPON_HAZARDCAN", "WEAPON_NIGHTSTICK", "WEAPON_HOMINGLAUNCHER", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_HEAVYSNIPER", "WEAPON_GOLFCLUB", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_APPISTOL", "WEAPON_GRENADELAUNCHER_SMOKE", "WEAPON_KNIFE", "WEAPON_GUSENBERG", "WEAPON_MOLOTOV", "WEAPON_FIREWORK", "WEAPON_FLAREGUN", "WEAPON_SNIPERRIFLE", "WEAPON_METALDETECTOR", "WEAPON_COMBATMG", "WEAPON_COMBATPISTOL", "WEAPON_SPECIALCARBINE_MK2"}

CreateThread(function()
    while true do
        local WeaponCount = 0
        local Ped = PlayerPedId()
        if Ped == nil then return end
        for i = 1, #allWeaponHashes do
            local Hash = GetHashKey(allWeaponHashes[i])
            if HasPedGotWeapon(Ped, Hash, false) then
                WeaponCount = WeaponCount + 1
            end
        end
        if WeaponCount > 0 then
            TriggerServerEvent("h_loadout:server:loadoutcheck",WeaponCount)
        end
        Wait(30000)
    end
end)
